/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  docs: {
    如何学习: [
      'resources/learn_resource',
      'resources/how_to_blockchain',
      'resources/video',
      'resources/node_template_help',
    ],
    Substrate文档: {
      Welcome: [
        'substrate/welcome/substrate-welcome',
        'substrate/welcome/substrate-blockchain-basics',
        'substrate/substrate-architecture',
      ],
      安装: [
        'substrate/install/substrate-install-macos',
        'substrate/install/substrate-install-linux',
        'substrate/install/substrate-install-windows',
      ],
      深入学习: [
        'substrate/substrate-account',
        'substrate/substrate-consensus',
        'substrate/substrate-cryptography',
        'substrate/substrate-network-nodes',
        'substrate/substrate-transaction-lifecycle',
        'substrate/extrinsics',
        'substrate/substrate-developer-tools',
        'substrate/substrate-light-clients-in-substrate-connect',
        'substrate/substrate-offchain-operation',
        'substrate/substrate-runtime-development',
        'substrate/substrate-rust-toolchain',
        'substrate/substrate-rust',
        'substrate/troubleshoot-rust-issues',
        'substrate/substrate-state-transition',
        'substrate/substrate-transactions-types',
        'substrate/substrate-xcm-communication',
      ],
    },
    Polkadot文档: [
      'polkadot/agile_coretime',
    ],
    公链开发: [
      'dappchain/install',
      'dappchain/setup_local_network',
      'dappchain/add_custom_module',
      'dappchain/add_test',
      'dappchain/add_ui'
    ],
    联盟链开发: [
      'consortium/features',
    ]
  }
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
